### ISSUE TITLE
"The Content-MD5 you specified did not match what we received" when uploading .txt 

### ISSUE THREAD

**Issue by cboulanger** [tnajdek/zotero-api-client#22]
I am experiencing a weird behavior that when I try to upload a text-only attachment, I invariably get the following error message: 

```
ErrorResponse: Upload stage 2: 400: Bad Request
    at throwErrorResponse (/Users/cboulanger/Code/zfrsoz/node_modules/zotero-api-client/src/request.js:149:8)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async request (/Users/cboulanger/Code/zfrsoz/node_modules/zotero-api-client/src/request.js:340:6)
    at async execute (/Users/cboulanger/Code/zfrsoz/node_modules/zotero-api-client/src/api.js:665:13)
    at async Attachment.upload (/Users/cboulanger/Code/zfrsoz/src/zotero/index.js:481:9)
    at async Object.extractText (/Users/cboulanger/Code/zfrsoz/src/sync.js:393:9)
    at async /Users/cboulanger/Code/zfrsoz/src/index.js:70:9 {
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: false, error: null },
    [Symbol(Response internals)]: {
      url: 'https://zoterofilestorage.s3.us-east-1.amazonaws.com/',
      status: 400,
      statusText: 'Bad Request',
      headers: [Headers],
      counter: 0
    }
  },
  reason: '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<Error><Code>BadDigest</Code><Message>The Content-MD5 you specified did not match what we received.</Message><ExpectedDigest>d530c9e6ecaf0cff76ddc56f2fbe81e1</ExpectedDigest><CalculatedDigest>kAZn6nEde6Giw3e5UiHI3Q==</CalculatedDigest><RequestId>PRYMARR14QG1R3ZD</RequestId><HostId>WNKXSjy4QemC5/8NJFevifr7n2a4tTUNLh29nWy/MyaC6uk4giVRmhIWUBgkwX+1A+S+/juLDvw=</HostId></Error>',
  options: {
    apiAuthorityPart: 'api.zotero.org',
    cache: 'default',
    contentType: 'application/x-www-form-urlencoded',
    credentials: 'omit',
    format: null,
    method: 'post',
    mode: 'cors',
    pretend: false,
    redirect: 'follow',
    resource: { library: 'g2829873', items: 'WWE84R7Z', file: null },
    retry: 0,
    retryDelay: null,
    uploadRegisterOnly: null,
    global: Object [global] {
      global: [Circular],
      clearInterval: [Function: clearInterval],
      clearTimeout: [Function: clearTimeout],
      setInterval: [Function: setInterval],
      setTimeout: [Function],
      queueMicrotask: [Function: queueMicrotask],
      clearImmediate: [Function: clearImmediate],
      setImmediate: [Function],
      fetch: [Function],
      Response: [class Response],
      Headers: [class Headers],
      Request: [class Request]
    },
    clearInterval: [Function: clearInterval],
    clearTimeout: [Function: clearTimeout],
    setInterval: [Function: setInterval],
    setTimeout: [Function: setTimeout] {
      [Symbol(nodejs.util.promisify.custom)]: [Function]
    },
    queueMicrotask: [Function: queueMicrotask],
    clearImmediate: [Function: clearImmediate],
    setImmediate: [Function: setImmediate] {
      [Symbol(nodejs.util.promisify.custom)]: [Function]
    },
    fetch: [Function: bound fetch] { polyfill: true },
    Response: [class Response],
    Headers: [class Headers],
    Request: [class Request],
    executors: [ [AsyncFunction: request] ],
    zoteroApiKey: 'xxx',
    ifNoneMatch: '*',
    fileName: 'myfile.txt',
    file: ArrayBuffer {
      [Uint8Contents]: <7b 0a 20 20 20 20 22 69 74 65 6d 54 79 70 65 22 3a 20 22 61 74 74 61 63 68 6d 65 6e 74 22 2c 0a 20 20 20 20 22 6c 69 6e 6b 4d 6f 64 65 22 3a 20 22 69 6d 70 6f 72 74 65 64 5f 66 69 6c 65 22 2c 0a 20 20 20 20 22 74 69 74 6c 65 22 3a 20 22 22 2c 0a 20 20 20 20 22 61 63 63 65 73 73 44 61 74 65 22 3a 20 ... 8092 more bytes>,
      byteLength: 8192
    },
    mtime: null,
    body: undefined,
    retryCount: 0
  }
}
``` 

It works with no problems when I upload/replace a PDF attachment.

Any idea what could be the problem?

**Comment by cboulanger** [comment]
Investigating further, it doesn't happen with all files, just with a few, for example, this one:
[oai_www.digizeitschriften.de_PPN598190155_0001_LOG_0005.txt](https://github.com/tnajdek/zotero-api-client/files/6292666/oai_www.digizeitschriften.de_PPN598190155_0001_LOG_0005.txt). They upload fine when I drag them onto an item in the Zotero client. 

There seems to be a problem with calculating the hash of utf-8 files, and maybe the content-length of this file. See, for example, https://github.com/matt-filion/s3-db/issues/15

**Comment by tnajdek** [comment]
@cboulanger my guess is you're using underlying `buffer` property (one of my examples did that something like `filedata.buffer`). This is not needed and will actually return incorrect data for small files, just use the `filedata` instead.

**Comment by cboulanger** [comment]
You are right, I took this from your example. I'll test it with the Buffer object instead of the ArrayBuffer and report - sounds like that was the problem.

**Comment by tnajdek** [comment]
Ok cool, closing. Feel free to reopen if it was something else.
